In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [106]:
data=pd.read_csv(r"D:\programming languages\datasets\IPL\ipl.csv")

In [107]:
data

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [108]:
stadiums=data.venue.unique()
stadiums

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park'],
      dtype=object)

In [109]:
data.head(50)

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
5,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.5,2,0,0,0,222
6,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,3,0,0.6,3,0,0,0,222
7,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,3,0,1.1,3,0,0,0,222
8,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,7,0,1.2,7,0,4,0,222
9,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,11,0,1.3,11,0,8,0,222
10,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,17,0,1.4,17,0,14,0,222
11,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,21,0,1.5,21,0,18,0,222
12,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,21,0,1.6,21,0,18,0,222
13,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,21,0,2.1,21,0,18,0,222
14,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,21,0,2.2,21,0,18,0,222
15,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,22,0,2.3,22,0,18,0,222
16,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,26,0,2.4,26,0,22,0,222
17,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,27,0,2.5,27,0,23,0,222
18,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,27,0,2.6,27,0,23,0,222
19,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,32,0,3.0,32,0,23,0,222
20,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,38,0,3.1,38,0,29,0,222
21,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,39,0,3.2,39,0,29,0,222
22,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,AA Noffke,43,0,3.3,43,0,29,4,222
23,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,AA Noffke,43,0,3.4,43,0,29,4,222
24,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,AA Noffke,44,0,3.5,44,0,29,5,222
25,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,50,0,3.6,50,0,35,5,222
26,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,54,0,4.1,54,0,35,9,222
27,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,55,0,4.2,55,0,35,10,222
28,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,59,0,4.3,59,0,39,10,222
29,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,59,0,4.4,59,0,39,10,222
30,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,60,0,4.5,59,0,40,10,222
31,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,60,0,4.6,59,0,40,10,222
32,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,61,0,5.1,59,0,41,10,222
33,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,Z Khan,61,1,5.2,59,1,41,10,222
34,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,61,1,5.3,59,1,41,0,222
35,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,61,1,5.4,59,1,41,0,222
36,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,61,1,5.5,58,1,41,0,222
37,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,61,1,5.6,58,1,41,0,222
38,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,62,1,6.1,55,1,42,0,222
39,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,AA Noffke,63,1,6.2,52,1,42,1,222
40,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,64,1,6.3,47,1,43,1,222
41,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,AA Noffke,66,1,6.4,45,1,43,3,222
42,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,AA Noffke,67,1,6.5,46,1,43,4,222
43,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,68,1,6.6,47,1,44,4,222
44,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,68,1,7.1,47,1,44,4,222
45,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,69,1,7.2,47,1,45,4,222
46,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,70,1,7.3,44,1,45,5,222
47,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,71,1,7.4,44,1,46,5,222
48,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,RT Ponting,Z Khan,72,1,7.5,45,1,46,6,222
49,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,73,1,7.6,41,1,47,6,222

In [110]:
data.groupby("venue").mean()

,mid,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
venue,,,,,,,,,
Barabati Stadium,296.203271,77.839953,2.396028,9.776519,35.163551,1.086449,25.976636,9.102804,167.863318
Brabourne Stadium,256.798551,84.055797,1.965217,9.794275,36.776087,0.947826,28.935507,10.813768,180.468841
Buffalo Park,80.721053,65.768421,2.615789,9.727632,29.378947,1.100000,16.628947,6.360526,146.842105
De Beers Diamond Oval,88.646739,71.328804,2.698370,9.863587,32.565217,1.255435,17.994565,7.040761,158.059783
Dr DY Patil Sports Academy,145.022989,66.997605,3.281609,9.746264,29.957854,1.367816,19.214080,6.528257,147.568008
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,459.108715,71.816712,2.255166,9.812309,32.919137,1.088050,22.377358,7.876011,160.138365
Dubai International Cricket Stadium,400.942396,71.014977,2.633641,9.853456,31.051843,1.094470,21.826037,9.115207,148.993088
Eden Gardens,337.177756,74.815577,2.383317,9.696496,33.004682,1.155909,23.026812,9.076323,156.768903
Feroz Shah Kotla,338.070175,77.968025,2.491794,9.832159,34.007499,1.139785,26.349462,9.646435,164.921619
Green Park,580.010163,81.343496,2.806911,9.744106,35.168699,1.343496,22.296748,8.955285,161.284553
Himachal Pradesh Cricket Association Stadium,260.531839,77.756951,1.833184,9.786009,35.901345,0.803587,30.966816,12.512108,175.901345
Holkar Cricket Stadium,435.089141,72.914100,2.607780,9.769692,32.470016,1.199352,30.145867,7.659643,158.262561
JSCA International Stadium Complex,422.811231,69.222222,2.026284,9.689247,31.732378,1.015532,22.236559,7.370370,148.945042
Kingsmead,81.154824,74.971693,2.727325,9.825708,31.938186,1.287695,23.819757,7.838821,151.659734
M Chinnaswamy Stadium,334.152895,76.674728,2.268843,9.739635,34.868736,1.099288,27.850329,9.470240,169.657934
"MA Chidambaram Stadium, Chepauk",248.114869,78.525452,2.142163,9.837542,34.242632,0.997823,27.859678,9.826021,166.080208
Maharashtra Cricket Association Stadium,537.063483,77.658709,2.198047,9.734509,34.195876,1.029843,27.064026,10.706457,168.032556
Nehru Stadium,197.549098,66.507014,2.450902,9.794990,30.649299,1.044088,24.250501,7.412826,150.729459
New Wanderers Stadium,96.142714,65.379899,2.906533,9.836080,29.272362,1.215075,19.506533,5.708543,143.952764
Newlands,60.907734,66.903664,3.113976,9.845455,29.928087,1.343284,23.151967,6.063772,145.408412
OUTsurance Oval,98.976096,60.824701,2.697211,9.715936,27.115538,1.103586,21.446215,9.239044,134.820717
"Punjab Cricket Association IS Bindra Stadium, Mohali",552.435171,77.385246,2.084203,9.760060,34.843517,0.988823,28.788376,10.616244,165.102832
"Punjab Cricket Association Stadium, Mohali",242.536614,78.325171,2.426654,9.730021,34.425241,1.170238,25.748057,8.629385,164.482223
"Rajiv Gandhi International Stadium, Uppal",353.276128,72.484984,2.430410,9.834083,32.499743,1.125450,24.280762,8.111721,157.649562
"Sardar Patel Stadium, Motera",337.500000,77.720350,2.442722,9.840027,33.763477,1.154987,23.398922,8.888814,163.216981
Saurashtra Cricket Association Stadium,550.600488,81.579333,2.425549,9.852563,35.175753,1.091131,30.020342,9.796583,168.799024
Sawai Mansingh Stadium,214.379075,72.634550,2.416788,9.796326,31.614599,1.128954,22.641119,8.605839,156.028224
Shaheed Veer Narayan Singh International Stadium,464.991914,65.605121,2.823450,9.814825,29.493261,1.284367,21.001348,5.219677,146.481132
Sharjah Cricket Stadium,399.306452,72.232527,2.708333,9.878763,32.184140,1.126344,23.028226,8.618280,158.104839
Sheikh Zayed Stadium,397.891148,69.740431,2.253589,9.471172,31.692584,1.124402,23.967703,9.698565,150.739234
St George's Park,76.822989,75.078161,1.874713,9.765517,32.674713,0.847126,24.804598,10.813793,159.004598
Subrata Roy Sahara Stadium,314.309204,66.810642,2.290988,9.843576,30.068073,1.073346,21.131831,8.244487,147.710451
SuperSport Park,90.523602,70.962963,2.936819,9.809441,31.278141,1.212781,25.742193,7.426289,152.077705
"Vidarbha Cricket Association Stadium, Jamtha",151.345946,75.575676,3.110811,9.819459,32.186486,1.448649,23.186486,7.770270,149.337838
Wankhede Stadium,359.387628,75.165295,2.434166,9.782534,33.789586,1.127270,24.378831,8.406073,164.648411

In [111]:
data1=data[['venue','bat_team','bowl_team','batsman','bowler','runs','wickets','overs','total']]

In [112]:
data1

,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,total
0,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,222
1,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,222
2,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,222
3,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,222
4,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,222
...,...,...,...,...,...,...,...,...,...
76009,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,129
76010,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,129
76011,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,129
76012,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,129
76013,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,129

In [113]:
grouped_data=data1.groupby('venue')

In [114]:
grouped_data.mean()

,runs,wickets,overs,total
venue,,,,
Barabati Stadium,77.839953,2.396028,9.776519,167.863318
Brabourne Stadium,84.055797,1.965217,9.794275,180.468841
Buffalo Park,65.768421,2.615789,9.727632,146.842105
De Beers Diamond Oval,71.328804,2.698370,9.863587,158.059783
Dr DY Patil Sports Academy,66.997605,3.281609,9.746264,147.568008
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,71.816712,2.255166,9.812309,160.138365
Dubai International Cricket Stadium,71.014977,2.633641,9.853456,148.993088
Eden Gardens,74.815577,2.383317,9.696496,156.768903
Feroz Shah Kotla,77.968025,2.491794,9.832159,164.921619
Green Park,81.343496,2.806911,9.744106,161.284553
Himachal Pradesh Cricket Association Stadium,77.756951,1.833184,9.786009,175.901345
Holkar Cricket Stadium,72.914100,2.607780,9.769692,158.262561
JSCA International Stadium Complex,69.222222,2.026284,9.689247,148.945042
Kingsmead,74.971693,2.727325,9.825708,151.659734
M Chinnaswamy Stadium,76.674728,2.268843,9.739635,169.657934
"MA Chidambaram Stadium, Chepauk",78.525452,2.142163,9.837542,166.080208
Maharashtra Cricket Association Stadium,77.658709,2.198047,9.734509,168.032556
Nehru Stadium,66.507014,2.450902,9.794990,150.729459
New Wanderers Stadium,65.379899,2.906533,9.836080,143.952764
Newlands,66.903664,3.113976,9.845455,145.408412
OUTsurance Oval,60.824701,2.697211,9.715936,134.820717
"Punjab Cricket Association IS Bindra Stadium, Mohali",77.385246,2.084203,9.760060,165.102832
"Punjab Cricket Association Stadium, Mohali",78.325171,2.426654,9.730021,164.482223
"Rajiv Gandhi International Stadium, Uppal",72.484984,2.430410,9.834083,157.649562
"Sardar Patel Stadium, Motera",77.720350,2.442722,9.840027,163.216981
Saurashtra Cricket Association Stadium,81.579333,2.425549,9.852563,168.799024
Sawai Mansingh Stadium,72.634550,2.416788,9.796326,156.028224
Shaheed Veer Narayan Singh International Stadium,65.605121,2.823450,9.814825,146.481132
Sharjah Cricket Stadium,72.232527,2.708333,9.878763,158.104839
Sheikh Zayed Stadium,69.740431,2.253589,9.471172,150.739234
St George's Park,75.078161,1.874713,9.765517,159.004598
Subrata Roy Sahara Stadium,66.810642,2.290988,9.843576,147.710451
SuperSport Park,70.962963,2.936819,9.809441,152.077705
"Vidarbha Cricket Association Stadium, Jamtha",75.575676,3.110811,9.819459,149.337838
Wankhede Stadium,75.165295,2.434166,9.782534,164.648411

In [115]:
data.isna().sum()

mid               0
date              0
venue             0
bat_team          0
bowl_team         0
batsman           0
bowler            0
runs              0
wickets           0
overs             0
runs_last_5       0
wickets_last_5    0
striker           0
non-striker       0
total             0
dtype: int64

In [116]:
data.bat_team.unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [117]:
active_teams=['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians','Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils','Sunrisers Hyderabad']

In [118]:
data1=data[data.bat_team.isin(active_teams) & data.bowl_team.isin(active_teams)]

In [119]:
data.venue.unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park'],
      dtype=object)

In [120]:
stadiums=['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy','Himachal Pradesh Cricket Association Stadium','Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium','Maharashtra Cricket Association Stadium']

In [121]:
data2=data1[data1.venue.isin(stadiums)]
data2

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,UT Yadav,SL Malinga,106,9,18.1,29,4,4,1,107
75885,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,UT Yadav,SL Malinga,107,9,18.2,29,4,4,2,107
75886,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,9,18.3,28,4,4,2,107
75887,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,9,18.4,24,4,4,2,107
75888,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,10,18.5,23,5,4,2,107

In [122]:
data2.date.dtype

dtype('O')

In [123]:
data2.date=pd.to_datetime(data2.date)

C:\Users\Sharath chandra\anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [124]:
data2.date.dtype

dtype('<M8[ns]')

In [165]:
data3=data2.drop(['mid','batsman','bowler','striker','non-striker'],axis=1)
data3

,date,venue,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total
0,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,0,0.1,1,0,222
1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,0,0.2,1,0,222
2,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2,0,0.2,2,0,222
3,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2,0,0.3,2,0,222
4,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2,0,0.4,2,0,222
...,...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,106,9,18.1,29,4,107
75885,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,107,9,18.2,29,4,107
75886,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,107,9,18.3,28,4,107
75887,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,107,9,18.4,24,4,107
75888,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,107,10,18.5,23,5,107

In [168]:
data4=pd.get_dummies(data3,columns=['venue','bat_team','bowl_team'],drop_first=True)
data4

,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,...,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
0,2008-04-18,1,0,0.1,1,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2008-04-18,1,0,0.2,1,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2008-04-18,2,0,0.2,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,2008-04-18,2,0,0.3,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,2008-04-18,2,0,0.4,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,106,9,18.1,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75885,2017-05-19,107,9,18.2,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75886,2017-05-19,107,9,18.3,28,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75887,2017-05-19,107,9,18.4,24,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75888,2017-05-19,107,10,18.5,23,5,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [169]:
data4.reset_index(inplace=True)
data4

,index,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,...,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
0,0,2008-04-18,1,0,0.1,1,0,222,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,2008-04-18,1,0,0.2,1,0,222,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2,2008-04-18,2,0,0.2,2,0,222,0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,2008-04-18,2,0,0.3,2,0,222,0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,2008-04-18,2,0,0.4,2,0,222,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,75884,2017-05-19,106,9,18.1,29,4,107,0,0,...,0,0,0,0,0,0,1,0,0,0
40972,75885,2017-05-19,107,9,18.2,29,4,107,0,0,...,0,0,0,0,0,0,1,0,0,0
40973,75886,2017-05-19,107,9,18.3,28,4,107,0,0,...,0,0,0,0,0,0,1,0,0,0
40974,75887,2017-05-19,107,9,18.4,24,4,107,0,0,...,0,0,0,0,0,0,1,0,0,0
40975,75888,2017-05-19,107,10,18.5,23,5,107,0,0,...,0,0,0,0,0,0,1,0,0,0

In [170]:
data4.drop('index',axis=1,inplace=True)
data4

,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,...,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
0,2008-04-18,1,0,0.1,1,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2008-04-18,1,0,0.2,1,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2008-04-18,2,0,0.2,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,2008-04-18,2,0,0.3,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,2008-04-18,2,0,0.4,2,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,2017-05-19,106,9,18.1,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40972,2017-05-19,107,9,18.2,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40973,2017-05-19,107,9,18.3,28,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40974,2017-05-19,107,9,18.4,24,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40975,2017-05-19,107,10,18.5,23,5,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [171]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [172]:
columns_to_be_scaled=['runs','wickets','overs','total']
scaled_columns=scaler.fit_transform(data3[columns_to_be_scaled])
scaled_df=pd.DataFrame(scaled_columns,columns=columns_to_be_scaled)
scaled_df

           runs  wickets     overs     total
0      0.004065      0.0  0.005102  0.865922
1      0.004065      0.0  0.010204  0.865922
2      0.008130      0.0  0.010204  0.865922
3      0.008130      0.0  0.015306  0.865922
4      0.008130      0.0  0.020408  0.865922
...         ...      ...       ...       ...
40971  0.430894      0.9  0.923469  0.223464
40972  0.434959      0.9  0.928571  0.223464
40973  0.434959      0.9  0.933673  0.223464
40974  0.434959      0.9  0.938776  0.223464
40975  0.434959      1.0  0.943878  0.223464

[40976 rows x 4 columns]

In [173]:
data4.drop(columns_to_be_scaled,axis=1,inplace=True)
data4

,date,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,...,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
0,2008-04-18,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2008-04-18,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,2017-05-19,29,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
40972,2017-05-19,29,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
40973,2017-05-19,28,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
40974,2017-05-19,24,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
40975,2017-05-19,23,5,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [174]:
data5=pd.concat([data4,scaled_df],axis=1)
data5

,date,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,...,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs,total
0,2008-04-18,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0.004065,0.0,0.005102,0.865922
1,2008-04-18,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0.004065,0.0,0.010204,0.865922
2,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.010204,0.865922
3,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.015306,0.865922
4,2008-04-18,2,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.020408,0.865922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,2017-05-19,29,4,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0.430894,0.9,0.923469,0.223464
40972,2017-05-19,29,4,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.928571,0.223464
40973,2017-05-19,28,4,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.933673,0.223464
40974,2017-05-19,24,4,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.938776,0.223464
40975,2017-05-19,23,5,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0.434959,1.0,0.943878,0.223464

In [175]:
data3=data5

In [176]:
training_data=data3[data3.date.dt.year<2016].drop('date',axis=1)
training_data

,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,"venue_Punjab Cricket Association Stadium, Mohali",...,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs,total
0,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0.004065,0.0,0.005102,0.865922
1,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0.004065,0.0,0.010204,0.865922
2,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.010204,0.865922
3,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.015306,0.865922
4,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0.008130,0.0,0.020408,0.865922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34895,57,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0.776423,0.5,0.979592,0.754190
34896,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0.780488,0.5,0.984694,0.754190
34897,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0.804878,0.5,0.989796,0.754190
34898,58,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0.821138,0.5,0.994898,0.754190
34899,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0.821138,0.5,1.000000,0.754190

In [177]:
testing_data=data3[data3.date.dt.year>=2016].drop('date',axis=1)
testing_data

,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,"venue_Punjab Cricket Association Stadium, Mohali",...,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs,total
34900,4,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0.016260,0.0,0.005102,0.173184
34901,4,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0.016260,0.0,0.010204,0.173184
34902,5,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0.020325,0.0,0.010204,0.173184
34903,6,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0.024390,0.0,0.015306,0.173184
34904,6,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0.024390,0.0,0.020408,0.173184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,29,4,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0.430894,0.9,0.923469,0.223464
40972,29,4,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.928571,0.223464
40973,28,4,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.933673,0.223464
40974,24,4,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0.434959,0.9,0.938776,0.223464
40975,23,5,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0.434959,1.0,0.943878,0.223464

In [178]:
x_train=training_data.drop(['total'],axis=1)
x_train

,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,"venue_Punjab Cricket Association Stadium, Mohali",...,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs
0,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0.004065,0.0,0.005102
1,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0.004065,0.0,0.010204
2,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0.008130,0.0,0.010204
3,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0.008130,0.0,0.015306
4,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0.008130,0.0,0.020408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34895,57,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.776423,0.5,0.979592
34896,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.780488,0.5,0.984694
34897,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.804878,0.5,0.989796
34898,58,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.821138,0.5,0.994898
34899,56,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.821138,0.5,1.000000

In [179]:
x_test=testing_data.drop('total',axis=1)
x_test

,runs_last_5,wickets_last_5,venue_Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,venue_Eden Gardens,venue_Feroz Shah Kotla,venue_Himachal Pradesh Cricket Association Stadium,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",venue_Maharashtra Cricket Association Stadium,"venue_Punjab Cricket Association Stadium, Mohali",...,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad,runs,wickets,overs
34900,4,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.016260,0.0,0.005102
34901,4,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.016260,0.0,0.010204
34902,5,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.020325,0.0,0.010204
34903,6,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.024390,0.0,0.015306
34904,6,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0.024390,0.0,0.020408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40971,29,4,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0.430894,0.9,0.923469
40972,29,4,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0.434959,0.9,0.928571
40973,28,4,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0.434959,0.9,0.933673
40974,24,4,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0.434959,0.9,0.938776
40975,23,5,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0.434959,1.0,0.943878

In [180]:
y_train=training_data.total
y_train

0        0.865922
1        0.865922
2        0.865922
3        0.865922
4        0.865922
           ...
34895    0.754190
34896    0.754190
34897    0.754190
34898    0.754190
34899    0.754190
Name: total, Length: 34900, dtype: float64

In [181]:
y_test=testing_data.total
y_test

34900    0.173184
34901    0.173184
34902    0.173184
34903    0.173184
34904    0.173184
           ...
40971    0.223464
40972    0.223464
40973    0.223464
40974    0.223464
40975    0.223464
Name: total, Length: 6076, dtype: float64

In [196]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import r2_score

In [197]:
ridge = Ridge()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40]}
ridge_regressor = RandomizedSearchCV(ridge,parameters,cv=10,scoring='neg_mean_squared_error')
ridge_regressor.fit(x_train,y_train)

C:\Users\Sharath chandra\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.31964e-22): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
C:\Users\Sharath chandra\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.31964e-17): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,

RandomizedSearchCV(cv=10, estimator=Ridge(),
                   param_distributions={'alpha': [1e-15, 1e-10, 1e-08, 0.001,
                                                  0.01, 1, 5, 10, 20, 30, 35,
                                                  40]},
                   scoring='neg_mean_squared_error')

In [202]:
ridge_regressor.score(x_test,y_test)

-0.011831959397677276

In [203]:
prediction_r = ridge_regressor.predict(x_test)
r2_score(y_test,prediction_r)

0.541444571416551